spring:
  devtools:
    restart:
      trigger-file: "reloadtrigger"

server:
  port: 8080



management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: ""
  health:
   show-details: always

